##################################################################################################
  # 用户服务
  ##################################################################################################
---
apiVersion: v1
kind: Service
metadata:
  name: user
  namespace: {{ include "professional.namespace" . }}
  labels:
    {{- include "professional.labels" . | nindent 4 }}
    app: user
spec:
  ports:
    - port: {{ .Values.user.service.port }}
      name: http2-grpc
      protocol: TCP
    - port: {{ .Values.user.service.gwport }}
      name: http-gw
      protocol: TCP
  selector:
    {{- include "professional.labels" . | nindent 4 }}
    app: user
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ include "professional.namespace" . }}
  name: user-v1
  labels:
    {{- include "professional.labels" . | nindent 4 }}
    app: user
    version: v1
spec:
  replicas: {{ .Values.user.replicas }}
  selector:
    matchLabels:
      {{- include "professional.labels" . | nindent 6 }}
      app: user
      version: v1
  template:
    metadata:
      namespace: {{ include "professional.namespace" . }}
      labels:
        {{- include "professional.labels" . | nindent 8 }}
        app: user
        version: v1
        lastUpdated: {{ .Values.lastUpdated }}
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      serviceAccountName: {{ include "professional.name" . }}
      imagePullSecrets:
        - name: aliyun
      containers:
        - name: user
          image:
            {{ .Values.user.image.imageRegistry}}:{{ .Values.user.image.tag }}
          imagePullPolicy: Always
          env:
            - name: DOMAIN
              value: {{ .Values.env.domain }}
          ports:
            - containerPort: {{ .Values.user.service.port }}
          resources:
            requests:
              cpu: {{ .Values.user.requests.cpu }}
              memory: {{ .Values.user.requests.memory }}
          volumeMounts:
            - name: user-volume
              mountPath: /deploy/helm/config/
      volumes:
        - name: user-volume
          configMap:
            name: user-cm
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: user-cm
  namespace: {{ include "professional.namespace" . }}
  labels:
    {{- include "professional.labels" . | nindent 4 }}
data:
  user.yaml: |
    {{ .Files.Get "config/user.yaml" | nindent 4 }}
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: user
  namespace: {{ include "professional.namespace" . }}
  labels:
    {{- include "professional.labels" . | nindent 4 }}
    app: user
    version: v1
spec:
  hosts:
    - user
    - {{ .Values.gateway.hostname }}
  gateways:
    - {{ include "professional.name" . }}
  http:
    - match:
        - uri:
            prefix: /user/sw
        - uri:
            prefix: /user/docs
        - uri:
            prefix: /user/v1
      route:
        - destination:
            host: user
            port:
              number: {{ .Values.user.service.gwport }}
            subset: v1
          weight: 100
    - match:
        - uri:
            prefix: /user
      route:
        - destination:
            host: user
            port:
              number: {{ .Values.user.service.port }}
            subset: v1
          weight: 100
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: user
  namespace: {{ include "professional.namespace" . }}
  labels:
    {{- include "professional.labels" . | nindent 4 }}
    app: user
    version: v1
spec:
  host: user
  subsets:
    - labels:
        version: v1
      name: v1

