@startuml

participant "客户端" as client
participant "登陆服" as login
database "数据库" as mysql

autonumber
client-> login: 注册请求
login -> mysql: 存储
client <-- login: 注册响应

newpage
autonumber
client-> login: 登陆请求
login -> mysql : 检查用户数据
client <-- login: 登陆响应

newpage
autonumber
client-> login: 删除角色请求
login->mysql : 删除用户数据
client <- login: 删除角色响应

@enduml